name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  one:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: init
        run: |
          ls -lAog
          printf "First Job\n" >> job.file
          ls -lAog
      - name: loop
        continue-on-error: true
        run: |
          until [[ "${MINUTES_LEFT:=300}" = 0 ]]; do
            printf "Please wait %s minute(s) ...\n" "${MINUTES_LEFT}"
            sleep 1m
            MINUTES_LEFT=$((MINUTES_LEFT - 1))
          done
          unset MINUTES_LEFT
          exit 0
  two:
    runs-on: ubuntu-latest
    needs: one

    steps:
      - uses: actions/checkout@v2

      - name: init
        run: |
          ls -lAog
          printf "Second Job\n" >> job.file
          ls -lAog
      - name: loop
        continue-on-error: true
        run: |
          until [[ "${MINUTES_LEFT:=300}" = 0 ]]; do
            printf "Please wait %s minute(s) ...\n" "${MINUTES_LEFT}"
            sleep 1m
            MINUTES_LEFT=$((MINUTES_LEFT - 1))
          done
          unset MINUTES_LEFT
          exit 0
  three:
    runs-on: ubuntu-latest
    needs: [one, two]

    steps:
      - uses: actions/checkout@v2

      - name: init
        run: |
          ls -lAog
          printf "Third Job\n" >> job.file
          ls -lAog
      - name: loop
        continue-on-error: true
        run: |
          until [[ "${MINUTES_LEFT:=300}" = 0 ]]; do
            printf "Please wait %s minute(s) ...\n" "${MINUTES_LEFT}"
            sleep 1m
            MINUTES_LEFT=$((MINUTES_LEFT - 1))
          done
          unset MINUTES_LEFT
          exit 0
