name: 'Delete old artifacts'
on:
  push:
    paths:
     - '.github/workflows/purge-artifacts-action.yml'
  schedule:
    - cron: '0 */6 * * *' # every hour

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 2days # Setting this to 0 will delete all artifacts
