name: MLBCI

on:
  workflow_dispatch:
    inputs:
      ScriptURL:
        description: "Script URL to Run"
        required: true
        type: string

env:
  SOURCERY: ${{ secrets.SOURCERY }}
  ScriptURL: ${{ github.event.inputs.ScriptURL }}
  RCLONE_CONFIG_URL: ${{ secrets.RCLONE_CONFIG_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: rokibhasansagar/custom_workflows/git_config@main
        env:
          PAT: ${{ secrets.GH_TOKEN }}

      - name: Checkout EncToolZ
        env:
          ReqdEncToolZ: "ftools mtools rtools"
        run: |
          eval 'set -eo pipefail' 2>/dev/null && eval 'set +o history' 2>/dev/null
          echo "$SOURCERY" | base64 -d > SOURCERY
          source ./SOURCERY &>/dev/null && rm -f ./SOURCERY && eval 'set -o history' 2>/dev/null
          wget -q "https://github.com/ZeoRexDevs/QZMir/raw/main/21-EncTool-b473ab7b69f5"
          DEOBFUS ./21-EncTool-b473ab7b69f5

      - name: Run Script
        run: |
          curl -sL "${ScriptURL}" | bash
